name: Build Android App

on:
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'Who triggered this workflow'
        required: false
        default: 'manual'
        type: string
      timestamp:
        description: 'When this workflow was triggered'
        required: false
        type: string
  push:
    branches:
      - main  # O workflow será disparado quando houver mudanças na branch 'main'
  pull_request:
    branches:
      - main  # O workflow será disparado quando houver um PR para a branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos a última versão do Ubuntu para o ambiente de build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Baixa o código do repositório

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with Gradle
        run: ./gradlew build # Executa a build do Gradle para compilar o APK

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/apk/debug/app-debug.apk  # Caminho do APK gerado
